# Railway Configuration for VIT Random Video Chat
[build]
command = "npm install && npm run build"

[deploy]
startCommand = "npm run start:railway"

[env]
NODE_ENV = "production"
PORT = "3001"
NEXT_PUBLIC_SOCKET_URL = "${{RAILWAY_PUBLIC_DOMAIN}}"

# Health check
[healthcheck]
path = "/api/health"
interval = "30s"
timeout = "10s"
retries = 3